# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  
  # Install dependencies before building docs
  jobs:
    pre_install:
      # Install the package with docs dependencies
      - pip install -e .[docs]

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

# Build PDF & ePub versions
formats:
  - pdf
  - epub