name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python
      run: uv python install 3.12
      
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y make
      
    - name: Install dependencies
      run: uv sync --extra docs
      
    - name: Debug - Check environment
      run: |
        echo "Current directory:"
        pwd
        echo "Docs directory contents:"
        ls -la docs/
        echo "Python version:"
        uv run python --version
        echo "Sphinx version:"
        uv run sphinx-build --version
        
    - name: Build documentation
      run: |
        cd docs
        echo "Building documentation..."
        uv run make html
        
    - name: Check for broken links
      run: |
        cd docs
        uv run make linkcheck
      continue-on-error: true
      
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/build/html/
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true